<div id="menu">
    <img src="img/BIM_Srbija_logo_small.jpg" name="logo_small" alt="Bim Srbija">
    <ul>
        <li><a href="index.php">Početna</a></li>
        <li><a href="o-udruzenju.php">O Udruženju</a></li>
        <li><a href="organi-udruzenja.php">Organi udruženja</a></li>
        <li><a href="clanovi-udruzenja.php">Članovi udruženja</a></li>
        <li><a href="dokumenta.php">Dokumenti</a></li>
        <li><a href="dogadjaji.php">Događaji</a></li>
        <li><a href="kontakt.php">Kontakt</a></li>
        <li><a href="en/index.php"><img src="img/flag1.png"></a></li>
    </ul>
</div>