 <div id="header-sms">
            <div id="menu-sms">
                <a href="index.php" style="margin-bottom:0;"><img src="img/BIM_Srbija_logo_small.jpg" name="logo_small" alt="Bim Srbija"></a>
                <i class="fas fa-bars"></i>
            </div>
        </div>
        <ul id="main-nav-ss">
            <li><a href="index.php">Početna</a></li>
            <li><a href="o-udruzenju.php">O Udruženju</a></li>
            <li><a href="organi-udruzenja.php">Organi udruženja</a></li>
            <li><a href="clanovi-udruzenja.php">Članovi udruženja</a></li>
            <li><a href="dokumenta.php">Dokumenti</a></li>
            <li><a href="dogadjaji.php">Događaji</a></li>
            <li><a href="kontakt.php">Kontakt</a></li>
            <li><a href="en/index.php"><img src="img/flag1.png"></a></li>
        </ul>
<div id="sp-menu">
    <a href="index.php" style="margin-bottom:0;"><img src="img/BIM_Srbija_logo_small.jpg" name="logo_small" alt="Bim Srbija"></a>
    <ul>
        <li><a href="index.php">Početna</a></li>
        <li><a href="o-udruzenju.php">O Udruženju</a></li>
        <li><a href="organi-udruzenja.php">Organi udruženja</a></li>
        <li><a href="clanovi-udruzenja.php">Članovi udruženja</a></li>
        <li><a href="dokumenta.php">Dokumenti</a></li>
        <li><a href="dogadjaji.php">Događaji</a></li>
        <li><a href="kontakt.php">Kontakt</a></li>
    </ul>
</div>