<div id="menu">
    <a href="../index.php" name="logo" style="margin-bottom:0;"><img src="../img/BIM_Srbija_logo_small.jpg" name="logo_small" alt="Bim Srbija"></a>
    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="about-us.php">About Us</a></li>
        <li><a href="representatives.php">Representatives</a></li>
        <li><a href="members.php">Members</a></li>
        <li><a href="documents.php">Documents</a></li>
        <li><a href="events.php">Events</a></li>
        <li><a href="contact.php">Contact</a></li>
        <li><a href="../index.php" style="margin:0;"><img src="../img/flag2.png"></a></li>
    </ul>
</div>